// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using QLNH_APIs.Data;

#nullable disable

namespace QLNH_APIs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241030062216_Model")]
    partial class Model
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLNH_APIs.Models.BanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KhachhangId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("TrangthaiId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("KhachhangId");

                    b.HasIndex("TrangthaiId");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("QLNH_APIs.Models.DonviModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LoaidonviId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TenDonvi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("LoaidonviId");

                    b.ToTable("Donvi");
                });

            modelBuilder.Entity("QLNH_APIs.Models.HinhMonanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ItemModelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("ItemModelId");

                    b.ToTable("HinhMonan");
                });

            modelBuilder.Entity("QLNH_APIs.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonviId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("Gia")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Giamgia")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("LoaiMonanId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Tenmonan")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("DonviId");

                    b.HasIndex("LoaiMonanId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("QLNH_APIs.Models.KhachHangModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Sodienthoai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QLNH_APIs.Models.LoaidonviModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.ToTable("Loaidonvi");
                });

            modelBuilder.Entity("QLNH_APIs.Models.LoaiMonanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("parentId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("LoaiMonan");
                });

            modelBuilder.Entity("QLNH_APIs.Models.OrderItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Giaban")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("ItemId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("OrderModelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Vohieu")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderModelId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("QLNH_APIs.Models.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Sodonhang")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Tienthanhtoan")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Tonggia")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<bool>("Vohieu")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("QLNH_APIs.Models.TrangThaiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.ToTable("TrangThai");
                });

            modelBuilder.Entity("QLNH_APIs.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("OffDuty")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("VaitroId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("VaitroId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QLNH_APIs.Models.VaiTroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Tenvaitro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("QLNH_APIs.Models.BanModel", b =>
                {
                    b.HasOne("QLNH_APIs.Models.KhachHangModel", "Khachhang")
                        .WithMany()
                        .HasForeignKey("KhachhangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_APIs.Models.TrangThaiModel", "Trangthai")
                        .WithMany()
                        .HasForeignKey("TrangthaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");

                    b.Navigation("Trangthai");
                });

            modelBuilder.Entity("QLNH_APIs.Models.DonviModel", b =>
                {
                    b.HasOne("QLNH_APIs.Models.LoaidonviModel", "Loaidonvi")
                        .WithMany()
                        .HasForeignKey("LoaidonviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loaidonvi");
                });

            modelBuilder.Entity("QLNH_APIs.Models.HinhMonanModel", b =>
                {
                    b.HasOne("QLNH_APIs.Models.ItemModel", null)
                        .WithMany("HinhMonan")
                        .HasForeignKey("ItemModelId");
                });

            modelBuilder.Entity("QLNH_APIs.Models.ItemModel", b =>
                {
                    b.HasOne("QLNH_APIs.Models.DonviModel", "Donvi")
                        .WithMany()
                        .HasForeignKey("DonviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_APIs.Models.LoaiMonanModel", "LoaiMonan")
                        .WithMany()
                        .HasForeignKey("LoaiMonanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donvi");

                    b.Navigation("LoaiMonan");
                });

            modelBuilder.Entity("QLNH_APIs.Models.OrderItemModel", b =>
                {
                    b.HasOne("QLNH_APIs.Models.ItemModel", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_APIs.Models.OrderModel", null)
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderModelId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("QLNH_APIs.Models.UserModel", b =>
                {
                    b.HasOne("QLNH_APIs.Models.VaiTroModel", "Vaitro")
                        .WithMany()
                        .HasForeignKey("VaitroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaitro");
                });

            modelBuilder.Entity("QLNH_APIs.Models.ItemModel", b =>
                {
                    b.Navigation("HinhMonan");
                });

            modelBuilder.Entity("QLNH_APIs.Models.OrderModel", b =>
                {
                    b.Navigation("OrderItem");
                });
#pragma warning restore 612, 618
        }
    }
}
