// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using QLNH_APIs.Data;

#nullable disable

namespace QLNH_APIs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLNH_APIs.Models.Ban", b =>
                {
                    b.Property<int>("BanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BanId"), 1L, 1);

                    b.Property<int>("KhachhangId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TrangthaiId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("BanId");

                    b.HasIndex("KhachhangId");

                    b.HasIndex("TrangthaiId");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Donvi", b =>
                {
                    b.Property<int>("DonviId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonviId"), 1L, 1);

                    b.Property<int>("LoaidonviId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TenDonvi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("DonviId");

                    b.HasIndex("LoaidonviId");

                    b.ToTable("Donvi");
                });

            modelBuilder.Entity("QLNH_APIs.Models.HinhMonan", b =>
                {
                    b.Property<int>("HinhMonanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HinhMonanId"), 1L, 1);

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("HinhMonanId");

                    b.HasIndex("ItemId");

                    b.ToTable("HinhMonan");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"), 1L, 1);

                    b.Property<int>("DonviId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("Gia")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Giamgia")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("LoaiMonanId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tenmonan")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("ItemId");

                    b.HasIndex("DonviId");

                    b.HasIndex("LoaiMonanId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("QLNH_APIs.Models.KhachHang", b =>
                {
                    b.Property<int>("KhachhangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachhangId"), 1L, 1);

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sodienthoai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("KhachhangId");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Loaidonvi", b =>
                {
                    b.Property<int>("LoaidonviId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaidonviId"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("LoaidonviId");

                    b.ToTable("Loaidonvi");
                });

            modelBuilder.Entity("QLNH_APIs.Models.LoaiMonan", b =>
                {
                    b.Property<int>("LoaiMonanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiMonanId"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("parentId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("LoaiMonanId");

                    b.ToTable("LoaiMonan");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sodonhang")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Tienthanhtoan")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Tonggia")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<bool>("Vohieu")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("QLNH_APIs.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"), 1L, 1);

                    b.Property<double>("Giaban")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("ItemId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Vohieu")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("QLNH_APIs.Models.TrangThai", b =>
                {
                    b.Property<int>("TrangthaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrangthaiId"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("TrangthaiId");

                    b.ToTable("TrangThai");
                });

            modelBuilder.Entity("QLNH_APIs.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("OffDuty")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("VaitroId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("VaitroId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QLNH_APIs.Models.VaiTro", b =>
                {
                    b.Property<int>("VaitroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaitroId"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayCapNhat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tenvaitro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Xoa")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("VaitroId");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Ban", b =>
                {
                    b.HasOne("QLNH_APIs.Models.KhachHang", "Khachhang")
                        .WithMany()
                        .HasForeignKey("KhachhangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_APIs.Models.TrangThai", "Trangthai")
                        .WithMany()
                        .HasForeignKey("TrangthaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");

                    b.Navigation("Trangthai");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Donvi", b =>
                {
                    b.HasOne("QLNH_APIs.Models.Loaidonvi", "Loaidonvi")
                        .WithMany()
                        .HasForeignKey("LoaidonviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loaidonvi");
                });

            modelBuilder.Entity("QLNH_APIs.Models.HinhMonan", b =>
                {
                    b.HasOne("QLNH_APIs.Models.Item", null)
                        .WithMany("HinhMonan")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Item", b =>
                {
                    b.HasOne("QLNH_APIs.Models.Donvi", "Donvi")
                        .WithMany()
                        .HasForeignKey("DonviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_APIs.Models.LoaiMonan", "LoaiMonan")
                        .WithMany()
                        .HasForeignKey("LoaiMonanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donvi");

                    b.Navigation("LoaiMonan");
                });

            modelBuilder.Entity("QLNH_APIs.Models.OrderItem", b =>
                {
                    b.HasOne("QLNH_APIs.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_APIs.Models.Order", null)
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("QLNH_APIs.Models.User", b =>
                {
                    b.HasOne("QLNH_APIs.Models.VaiTro", "Vaitro")
                        .WithMany()
                        .HasForeignKey("VaitroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaitro");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Item", b =>
                {
                    b.Navigation("HinhMonan");
                });

            modelBuilder.Entity("QLNH_APIs.Models.Order", b =>
                {
                    b.Navigation("OrderItem");
                });
#pragma warning restore 612, 618
        }
    }
}
